#!/bin/sh /etc/rc.common
START=97
STOP=10

export IPSET_NAME=gfwlist
export SOCK5_PORT=1080
export REDIR_PORT=1081
export DNS_PORT=1053

boot() {
    return 0
}

reload() {
    restart
    return 0
}

restart() {
    stop
    sleep 1
    start
}

start() {
    date >> /var/log/test.log
    echo 'start begin' >> /var/log/test.log
    service_start /usr/bin/ss-local -c /etc/shadowsocks.json -A -u -l $SOCK5_PORT -f /var/run/ss-redir.pid
    service_start /usr/bin/ss-redir -c /etc/shadowsocks.json -A -u -l $REDIR_PORT -f /var/run/ss-redir.pid
    service_start /usr/bin/ss-tunnel -c /etc/shadowsocks.json -A -u -l $DNS_PORT -L 8.8.8.8:53 -f /var/run/ss-tunnel.pid
    ipset flush $IPSET_NAME || ipset -N $IPSET_NAME iphash
    iptables -t nat -A PREROUTING -p tcp -m set --match-set $IPSET_NAME dst -j REDIRECT --to-port $REDIR_PORT
    iptables -t nat -A OUTPUT -p tcp -m set --match-set $IPSET_NAME dst -j REDIRECT --to-port $REDIR_PORT
    /etc/init.d/dnsmasq restart

    echo 'start end' >> /var/log/test.log
}

stop() {
    date >> /var/log/test.log
    echo 'stop begin' >> /var/log/test.log
    service_stop /usr/bin/ss-local
    service_stop /usr/bin/ss-redir
    service_stop /usr/bin/ss-tunnel
    iptables -t nat -D PREROUTING -p tcp -m set --match-set $IPSET_NAME dst -j REDIRECT --to-port $REDIR_PORT
    iptables -t nat -D OUTPUT -p tcp -m set --match-set $IPSET_NAME dst -j REDIRECT --to-port $REDIR_PORT
    ipset flush $IPSET_NAME
    /etc/init.d/dnsmasq restart
    killall /usr/bin/ss-local
    killall /usr/bin/ss-redir
    killall /usr/bin/ss-tunnel
    echo 'stop end' >> /var/log/test.log
    return 0
}
